### ISSUE TITLE
Verbose mode

### ISSUE THREAD

**Issue by Dids** [funkhaus/fh-deploy#12]
I've been trying to look for a good way to deploy a Vue.js project to an SFTP server, and after setting up fh-deploy, I'm getting permissioin denied errors, even though I can deploy just fine with an SFTP client or by using `scp` directly.

It would be nice if there was a verbose mode, since I have no idea what's _actually_ wrong, as the credentials and host information are correct.

```
> fh-deploy testing

Using deploy target testing...
Error: Error: Permission denied
    at sftp.mkdir.catch.err (/Users/dids/<project>/node_modules/fh-deploy/src/deploy.js:59:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
Error during uploading. Not all files may be uploaded.
```

**Comment by Dids** [comment]
Figured out my issue though. Didn't realize `target` _only_ supported absolute paths, as I was trying to use a relative path instead.
